// <auto-generated />
using System;
using Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(ApiFinanceiroContext))]
    [Migration("20250122021318_Nomes")]
    partial class Nomes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entidades.CategoryMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("TypeMovementId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeMovementId");

                    b.ToTable("CategoriaMovis");
                });

            modelBuilder.Entity("Domain.Entidades.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("Domain.Entidades.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Lançamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Pagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("QuantidadeParcela")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoMovimentacaoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorJuros")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("TipoMovimentacaoId");

                    b.ToTable("Movimentacao");
                });

            modelBuilder.Entity("Domain.Entidades.TypeMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Entrada")
                        .HasColumnType("boolean");

                    b.Property<bool>("Saida")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("TipoMovimentacao");
                });

            modelBuilder.Entity("Domain.Entidades.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Domain.Entidades.CategoryMovement", b =>
                {
                    b.HasOne("Domain.Entidades.TypeMovement", "TypeMovement")
                        .WithMany()
                        .HasForeignKey("TypeMovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeMovement");
                });

            modelBuilder.Entity("Domain.Entidades.Movement", b =>
                {
                    b.HasOne("Domain.Entidades.TypeMovement", "TipoMovimentacao")
                        .WithMany()
                        .HasForeignKey("TipoMovimentacaoId");

                    b.Navigation("TipoMovimentacao");
                });
#pragma warning restore 612, 618
        }
    }
}
